name: CI Workflow
on:
  push:
    branches: ["main","tdd_repository"]
  pull_request:
    branches: ["main","tdd_repository"]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim
    defaults:
      run:
        working-directory: ./tdd
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
      - name: Lint with flake8
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --max-complexity=10 --max-line-length=127 --statistics
      - name: Run unit tests with pytests
        run: |
          pytest -v --tb=short --color=yes --cov=src --cov-report=term-missing
